install.packages("harmony")
install.packages("hdf5r")
install.packages("ggpmisc")  
install.packages("BiocManager") # Needed to install all Bioconductor packages

remotes::install_github("chris-mcginnis-ucsf/DoubletFinder")
remotes::install_version("Seurat", "4.4.0", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
#MAST for DE analysis
BiocManager::install("MAST")
install.packages("miscTools")
install.packages("tidyr")
if (!requireNamespace('BiocManager', quietly = TRUE))
  install.packages('BiocManager')
BiocManager::install('EnhancedVolcano', force=TRUE)
#GO 
BiocManager::install(version = '3.18')
BiocManager::install("clusterProfiler", version = "3.18",force = TRUE)
BiocManager::install("pathview",force = TRUE)
BiocManager::install("enrichplot",force = TRUE)
BiocManager::install("AnnotationDbi",force = TRUE)

organism = "org.Mm.eg.db" #for mouse dataset
organism = "org.Hs.eg.db" #for human dataset
BiocManager::install(organism, character.only = TRUE,force = TRUE)
# Load libraries installed
library(tidyverse)
library(ggpmisc)
library(gridExtra)
library(stringr)
library(data.table)
library(gridExtra)
library(dplyr)
library(purrr)
library(grid)
library(ggplot2)
library(lattice)
library(maditr)
library(pheatmap)
library(tidyverse)
library(patchwork)
library(viridis)
library(EnhancedVolcano)
library(cowplot)
library(clusterProfiler)
library(enrichplot)
library(tidyr)
library(reshape2)
library(miscTools)
library(tibble)
library(scales) 
library(organism, character.only = TRUE)
library(tidytext)  
library(progress)
library(readxl)
library(openxlsx)
library(Seurat)
library(SeuratObject)
library(hdf5r)
library(sctransform)
library(harmony)
library(DoubletFinder)
library(patchwork)
library(Matrix)
